import Head from "next/head"
import styles from "../styles/Home.module.css"

export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.nav}>
                <ul className={styles.nav__items}>
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/">About</a>
                    </li>
                    <li>
                        <a href="/">Contact</a>
                    </li>
                </ul>
            </div>

            <main class={styles.main}>
                <h1>Lorem, ipsum dolor.</h1>
            </main>

            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Lorem, ipsum dolor.
                </a>
            </footer>
        </>
    )
}
