import Head from "next/head"
import Home from "../components/Home"

const HomePage = ({ fetchedData }) => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Home data={fetchedData} />
        </>
    )
}

/*
    getStaticProps - fetch data at build time
    getServerSideProps - fetch data on request
    getStaticPaths - to dynamically generate paths based on the data we're fetching
*/

export const getStaticProps = async () => {
    const response = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=6")
    const fetchedData = await response.json()
    return {
        props: {
            fetchedData
        }
    }
}

export default HomePage
